### ISSUE TITLE
Fix dependency vulnerability minimist

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/tdm-calculator#336]
# Description
Cleanup current vulnerability

## Action Items
see below

## Resources
![Screen Shot 2020-04-11 at 10 12 27 AM](https://user-images.githubusercontent.com/37763229/79050153-fdd77980-7bdc-11ea-8c43-ba55cdeaed9c.png)

[file it appears in](https://github.com/hackforla/tdm-calculator/blob/develop/package-lock.json)
```yaml
        "minimist": {
          "version": "1.2.5",
          "resolved": "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz",
          "integrity": "sha512-FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==",
          "dev": true
        },
```
